(function(root,factory){const api=factory(root);if(typeof module==='object'&&module.exports)module.exports=api;if(root)root.RoleDeskOpportunityEngine=api})(typeof window!=='undefined'?window:globalThis,function(root){
  const stages=Object.freeze(['Discovered','Recommended','Shortlisted','Resume Ready','Cover Letter Ready','Applied','Follow-Up Needed','Interview Scheduled','Offer','Rejected','Closed / Not Relevant']);
  const applicationMethods=Object.freeze(['Company website','LinkedIn','Email','Referral','Recruiter','Job board','Other']);
  const clean=value=>String(value||'').trim(),number=value=>Number.isFinite(Number(value))?Number(value):0,clamp=value=>Math.max(0,Math.min(100,Math.round(value))),safeUrl=value=>/^https?:\/\/[^\s]+$/i.test(clean(value))?clean(value):'',daysOld=(value,now=new Date())=>{const date=new Date(value||0);return date.getTime()?Math.max(0,Math.floor((now-date)/86400000)):null};
  const legacyStages=Object.freeze({'Saved':'Shortlisted','Draft Prepared':'Cover Letter Ready','Ready to Apply':'Resume Ready','Proposal Sent':'Applied','Email Sent':'Applied','Client Replied':'Follow-Up Needed','Interview':'Interview Scheduled','Negotiation':'Interview Scheduled','Hired':'Offer','Completed':'Offer','Payment Received':'Offer','No Response':'Follow-Up Needed','Archived':'Closed / Not Relevant','Skipped':'Closed / Not Relevant','Submitted':'Applied','Proposal Drafted':'Cover Letter Ready'});
  function stageOf(item={}){return stages.includes(item.status)?item.status:(legacyStages[item.status]||'Discovered')}
  function contact(item={}){const email=clean(item.verifiedEmail||item.email||item.contactEmail),source=safeUrl(item.emailSourceUrl||item.contactSourceUrl||item.url),verified=Boolean(email&&(item.contactEmailVerified||item.verifiedEmail||/live api/i.test(item.sourceMethod||'')));return{verifiedEmail:verified?email:'',possibleEmail:verified?'':clean(item.possibleEmail||(!verified?email:'')),source,confidence:verified?'Verified from provided/public source':email?'Unverified — review source':'Not found',lastChecked:item.contactLastCheckedAt||item.updatedAt||item.createdAt||''}}
  function quality(item={},now=new Date()){
    const route=safeUrl(item.applicationUrl||item.url),description=clean(item.description||item.brief),company=clean(item.company||item.client),age=daysOld(item.publishedAt||item.date,now),hasSalary=Boolean(item.salary||number(item.pipelineValue||item.budget)),workMode=clean(item.workMode)||(item.remote?'remote':''),c=contact(item),warnings=[];
    let score=0;score+=route?22:0;score+=company&&!/unknown|confidential/i.test(company)?14:0;score+=description.length>=300?18:description.length>=100?10:0;score+=age===null?5:age<=14?14:age<=30?10:age<=60?5:0;score+=hasSalary?10:0;score+=workMode?7:0;score+=c.verifiedEmail?7:0;score+=item.source&&item.sourceMethod?8:4;
    if(!route)warnings.push('No direct application link found.');if(description.length<100)warnings.push('Low information job post.');if(age!==null&&age>45)warnings.push('This job may be old.');if(!c.verifiedEmail&&clean(item.email||item.possibleEmail))warnings.push('Email not verified.');if(item.possibleDuplicate)warnings.push('Possible duplicate.');if(!company||/unknown|confidential/i.test(company))warnings.push('Company identity needs review.');
    const value=clamp(score-(item.possibleDuplicate?15:0));return{score:value,label:value>=80?'High quality':value>=60?'Apply carefully':'Needs verification',warnings};
  }
  function readiness(profile={},item={}){
    const match=clamp(item.matchScore??item.skill),missing=(item.missingKeywords||[]).length,route=Boolean(safeUrl(item.applicationUrl||item.url)),c=contact(item),hasResume=Boolean(profile.text||profile.rawText||profile.experienceSummary||(profile.skills||[]).length),portfolioNeeded=/design|creative|writer|content|marketing|product/i.test(`${item.title||''} ${item.type||''}`),hasPortfolio=Boolean(safeUrl(profile.portfolioUrl)),coverReady=['Cover Letter Ready','Applied','Follow-Up Needed','Interview Scheduled','Offer'].includes(stageOf(item))||Boolean(item.coverLetterReady),locationKnown=Boolean(clean(item.country||item.location||item.workMode)),salaryKnown=Boolean(item.salary||number(item.pipelineValue||item.budget));
    let score=Math.round(match*.48);score+=hasResume?12:0;score+=Math.max(0,12-Math.min(12,missing*3));score+=route?8:0;score+=coverReady?7:0;score+=locationKnown?5:0;score+=salaryKnown?3:0;score+=c.verifiedEmail?3:0;score+=portfolioNeeded?(hasPortfolio?2:0):2;
    const gaps=[];if(!hasResume)gaps.push('review your resume');if(missing)gaps.push(`address ${missing} missing skill${missing===1?'':'s'}`);if(portfolioNeeded&&!hasPortfolio)gaps.push('add a relevant portfolio link');if(!coverReady)gaps.push('prepare a tailored cover letter');if(!route)gaps.push('verify the application route');const value=clamp(score),label=value>=80?'Ready to apply':value>=60?'Worth preparing':'Needs resume improvement',explanation=gaps.length?`${value}% ready — ${gaps.slice(0,2).join(' and ')}.`:`${value}% ready — core profile and application evidence are present. Review everything before applying.`;return{score:value,label,explanation,gaps};
  }
  function labels(profile={},item={},now=new Date()){const result=[],ready=readiness(profile,item),q=quality(item,now),age=daysOld(item.publishedAt||item.date,now),route=clean(item.applicationUrl||item.url),c=contact(item);if((item.matchScore??item.skill)>=80)result.push('Strong Match');else if(ready.score>=65)result.push('Worth Applying');else result.push('Needs Resume Improvement');if(ready.score<45)result.push('Low Priority');if(item.remote||/remote/i.test(item.workMode||item.location||item.country||''))result.push('Remote');if(/hybrid/i.test(item.workMode||''))result.push('Hybrid');if(age!==null&&age<=14)result.push('Recently Posted');if(route)result.push(/career/i.test(route)?'Company Careers Page':'Direct Apply');if(c.verifiedEmail)result.push('Recruiter Email Available');if(q.score<60)result.push('Apply Carefully');return[...new Set(result)]}
  function suggestedFollowUps(from=new Date()){return[3,5,7].map(days=>{const date=new Date(from);date.setDate(date.getDate()+days);return{days,date:date.toISOString().slice(0,10),label:`Follow up after ${days} days`}})}
  function nextAction(profile={},item={}){const stage=stageOf(item),ready=readiness(profile,item),c=contact(item),route=safeUrl(item.applicationUrl||item.url);if(['Applied','Follow-Up Needed'].includes(stage))return item.followup?.nextAt?`Follow up on ${item.followup.nextAt}.`:'Schedule a follow-up in 3–7 days.';if(stage==='Interview Scheduled')return'Prepare verified examples and interview questions.';if(ready.score<60)return ready.gaps[0]?`First: ${ready.gaps[0]}.`:'Review resume gaps before applying.';if(route)return'Review the packet, then apply through the official link.';if(c.verifiedEmail)return'Review and copy the recruiter email draft.';return'Find and verify an official application route.'}
  return Object.freeze({stages,applicationMethods,stageOf,contact,quality,readiness,labels,suggestedFollowUps,nextAction});
});
