(function(root){
  const engine=root.RoleDeskUniversalSearch,state=root.RoleDeskState,node=document.querySelector('#searchIntentPanel');if(!engine||!state||!node)return;
  const esc=value=>root.ScopeSecurity.escapeHtml(String(value??'')),owner=()=>localStorage.getItem('scope-cache-owner-v1')||'local',key=()=>`roledesk-search-intent-v1:${owner()}`,list=value=>String(value||'').split(',').map(item=>item.trim()).filter(Boolean);
  function read(){try{return JSON.parse(localStorage.getItem(key())||'null')}catch{return null}}
  function write(value){localStorage.setItem(key(),JSON.stringify(value));return value}
  function generated(){return engine.buildIntent(state.getProfile()||{})}
  function values(){return read()||generated()}
  function formIntent(){return{targetRole:document.querySelector('#intentTargetRole').value.trim(),alternateRoles:list(document.querySelector('#intentAlternateRoles').value),includeSkills:list(document.querySelector('#intentIncludeSkills').value),excludeSkills:list(document.querySelector('#intentExcludeSkills').value),industries:list(document.querySelector('#intentIndustries').value),location:document.querySelector('#intentLocation').value.trim(),remotePreference:document.querySelector('#intentRemote').value,jobType:document.querySelector('#intentJobType').value,seniority:document.querySelector('#intentSeniority').value,minimumMatch:Number(document.querySelector('#intentMinimum').value),includeFreelance:document.querySelector('#intentFreelance').checked,includeInternships:document.querySelector('#intentInternships').checked,includeMnc:document.querySelector('#intentMnc').checked}}
  function apply(intent){const query=document.querySelector('#liveSearchQuery'),minimum=document.querySelector('#liveMinScore');if(query)query.value=intent.targetRole||'';if(minimum&&[...minimum.options].some(option=>Number(option.value)===Number(intent.minimumMatch)))minimum.value=String(intent.minimumMatch);document.dispatchEvent(new CustomEvent('roledesk:search-intent-changed',{detail:intent}))}
  function render(force=false){const intent=force?write(generated()):values();node.innerHTML=`<div class="search-intent-head"><div><span class="eyebrow">Resume-based search intent</span><h3>Review what RoleDesk should search for</h3><p>Search terms are generated from your resume. Edit them if your target role is different.</p></div><button class="button secondary" id="regenerateSearchIntent" type="button">Regenerate from resume</button></div><div class="search-intent-grid"><label>Target role<input id="intentTargetRole" value="${esc(intent.targetRole)}" placeholder="Add a target role"></label><label>Alternate roles<textarea id="intentAlternateRoles">${esc((intent.alternateRoles||[]).join(', '))}</textarea></label><label>Skills to include<textarea id="intentIncludeSkills">${esc((intent.includeSkills||[]).join(', '))}</textarea></label><label>Skills to exclude<textarea id="intentExcludeSkills">${esc((intent.excludeSkills||[]).join(', '))}</textarea></label><label>Industries<textarea id="intentIndustries">${esc((intent.industries||[]).join(', '))}</textarea></label><label>Location<input id="intentLocation" value="${esc(intent.location)}" placeholder="Not assumed"></label><label>Remote preference<select id="intentRemote"><option value="">Not specified</option>${['Remote only','Hybrid','On-site','Flexible'].map(value=>`<option ${intent.remotePreference===value?'selected':''}>${value}</option>`).join('')}</select></label><label>Job type<select id="intentJobType">${['Any','Full-time','Contract','Freelance','Internship','Consultant'].map(value=>`<option ${intent.jobType===value?'selected':''}>${value}</option>`).join('')}</select></label><label>Seniority<select id="intentSeniority">${['seniority not confirmed','entry','associate','senior','lead','director'].map(value=>`<option ${intent.seniority===value?'selected':''}>${value}</option>`).join('')}</select></label><label>Minimum match<select id="intentMinimum">${[0,50,70,85].map(value=>`<option value="${value}" ${Number(intent.minimumMatch)===value?'selected':''}>${value?`${value}+`:'Show all'}</option>`).join('')}</select></label></div><div class="search-intent-checks"><label><input id="intentFreelance" type="checkbox" ${intent.includeFreelance?'checked':''}> Include freelance</label><label><input id="intentInternships" type="checkbox" ${intent.includeInternships?'checked':''}> Include internships</label><label><input id="intentMnc" type="checkbox" ${intent.includeMnc?'checked':''}> Include MNC career pages</label></div><button class="button primary" id="saveSearchIntent" type="button">Save search intent</button>`;
    document.querySelector('#regenerateSearchIntent').onclick=()=>{render(true);apply(values());root.toast?.('Search intent regenerated from your reviewed profile')};document.querySelector('#saveSearchIntent').onclick=()=>{const next=write(engine.buildIntent(state.getProfile()||{},formIntent()));apply(next);root.toast?.('Search intent saved')};apply(intent)
  }
  document.addEventListener('roledesk:auth-changed',()=>render());window.RoleDeskSearchIntent=Object.freeze({get:values,regenerate:()=>{render(true);return values()},render});render();
})(window);
